name: Docker build and push (release)
 
on:
  push:
    tags: 

  workflow_dispatch:

jobs:
  latest_versions:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      protobuf_version: ${{ steps.protobuf.outputs.protobuf_version }}
      compose_version: ${{ steps.compose.outputs.compose_version }}
      llvm_version: ${{ steps.llvm.outputs.llvm_version }}
    steps:
    - name: prepare
      run: |
        sudo apt-get update -qq && \
        sudo apt-get install --no-install-recommends -qqy \
          jq
    - name: find latest vrersions (protocol buffers)
      id: protobuf
      run: |
        PROTOCOL_BUFFERS_VERSION="$(curl -sSL https://api.github.com/repos/protocolbuffers/protobuf/releases/latest | jq -r .tag_name | cut -d'v' -f2)" && \
        echo "protobuf_version=${PROTOCOL_BUFFERS_VERSION}" >> $GITHUB_OUTPUT
    - name: find latest vrersions (docker compose)
      id: compose
      run: |
        COMPOSE_VERSION="$(curl -sSL https://api.github.com/repos/docker/compose/releases/latest | jq -r .tag_name)" && \
        echo "compose_version=${COMPOSE_VERSION}" >> $GITHUB_OUTPUT
    - name: find latest vrersions (llvm)
      id: llvm
      run: |
        LLVM_VERSION="$(curl -sSL https://api.github.com/repos/llvm/llvm-project/releases/latest | jq -r .tag_name | cut -d'-' -f2)" && \
        echo "llvm_version=${LLVM_VERSION}" >> $GITHUB_OUTPUT

  docker_build_push:
    needs: latest_versions
    strategy:
      matrix:
        versions: [
          { tag: 'compose', target: 'compose', distoribution: 'debian', debian-code-name: 'bullseye', java-version: '17', platforms: 'linux/amd64' },

          { tag: 'debian-bullseye', target: 'default', distoribution: 'debian', debian-code-name: 'bullseye', java-version: '17', platforms: 'linux/amd64' },
          { tag: 'compose-bullseye', target: 'compose', distoribution: 'debian', debian-code-name: 'bullseye', java-version: '17', platforms: 'linux/amd64' },

          { tag: 'compose-java11', target: 'compose', distoribution: 'debian', debian-code-name: 'bullseye', java-version: '11', platforms: 'linux/amd64' },
          { tag: 'compose-java17', target: 'compose', distoribution: 'debian', debian-code-name: 'bullseye', java-version: '17', platforms: 'linux/amd64' },

          { tag: 'debian-bullseye-java11', target: 'default', distoribution: 'debian', debian-code-name: 'bullseye', java-version: '11', platforms: 'linux/amd64' },
          { tag: 'compose-bullseye-java11', target: 'compose', distoribution: 'debian', debian-code-name: 'bullseye', java-version: '11', platforms: 'linux/amd64' },
          { tag: 'debian-bullseye-java17', target: 'default', distoribution: 'debian', debian-code-name: 'bullseye', java-version: '17', platforms: 'linux/amd64' },
          { tag: 'compose-bullseye-java17', target: 'compose', distoribution: 'debian', debian-code-name: 'bullseye', java-version: '17', platforms: 'linux/amd64' },

          { tag: 'debian-buster', target: 'default', distoribution: 'debian', debian-code-name: 'buster', java-version: '11', platforms: 'linux/amd64' },
          { tag: 'debian-buster-java11', target: 'default', distoribution: 'debian', debian-code-name: 'buster', java-version: '11', platforms: 'linux/amd64' },
          { tag: 'debian-buster-java17', target: 'default', distoribution: 'debian', debian-code-name: 'buster', java-version: '17', platforms: 'linux/amd64' },

          # { tag: 'ubuntu-jammy', target: 'default', distoribution: 'ubuntu', debian-code-name: 'jammy', java-version: '17', platforms: 'linux/amd64' },
          # { tag: 'compose-jammy', target: 'compose', distoribution: 'ubuntu', debian-code-name: 'jammy', java-version: '17', platforms: 'linux/amd64' },

          # { tag: 'ubuntu-jammy-java11', target: 'default', distoribution: 'ubuntu', debian-code-name: 'jammy', java-version: '11', platforms: 'linux/amd64' },
          # { tag: 'compose-jammy-java11', target: 'compose', distoribution: 'ubuntu', debian-code-name: 'jammy', java-version: '11', platforms: 'linux/amd64' },
          # { tag: 'ubuntu-jammy-java17', target: 'default', distoribution: 'ubuntu', debian-code-name: 'jammy', java-version: '17', platforms: 'linux/amd64' },
          # { tag: 'compose-jammy-java17', target: 'compose', distoribution: 'ubuntu', debian-code-name: 'jammy', java-version: '17', platforms: 'linux/amd64' },

          { tag: 'ubuntu-focal', target: 'default', distoribution: 'ubuntu', debian-code-name: 'focal', java-version: '11', platforms: 'linux/amd64' },
          { tag: 'ubuntu-focal-java11', target: 'default', distoribution: 'ubuntu', debian-code-name: 'focal', java-version: '11', platforms: 'linux/amd64' },
          { tag: 'ubuntu-focal-java17', target: 'default', distoribution: 'ubuntu', debian-code-name: 'focal', java-version: '17', platforms: 'linux/amd64' },

          { tag: 'compose-focal', target: 'compose', distoribution: 'ubuntu', debian-code-name: 'focal', java-version: '11', platforms: 'linux/amd64' },
          { tag: 'compose-focal-java11', target: 'compose', distoribution: 'ubuntu', debian-code-name: 'focal', java-version: '11', platforms: 'linux/amd64' },
          { tag: 'compose-focal-java17', target: 'compose', distoribution: 'ubuntu', debian-code-name: 'focal', java-version: '17', platforms: 'linux/amd64' }
        ]
    runs-on: ubuntu-latest
    steps:
    - name: prepare env
      env:
        PROTOCOL_BUFFERS_VERSION: ${{needs.latest_versions.outputs.protobuf_version}}
        COMPOSE_VERSION: ${{needs.latest_versions.outputs.compose_version}}
        LLVM_VERSION: ${{needs.latest_versions.outputs.llvm_version}}
        JAVA_VERSION: ${{ matrix.versions.java-version }}
        DISTORIBUTION: ${{ matrix.versions.distoribution }}
        DEBIAN_CODE_NAME: ${{ matrix.versions.debian-code-name }}
      run: |
          echo "LLVM_VERSION=$(echo ${LLVM_VERSION} | cut -d . -f1)" >> $GITHUB_ENV
          echo "PROTOCOL_BUFFERS_VERSION=${PROTOCOL_BUFFERS_VERSION}" >> $GITHUB_ENV
          echo "COMPOSE_VERSION=${COMPOSE_VERSION}" >> $GITHUB_ENV
          echo "JAVA_VERSION=${JAVA_VERSION}" >> $GITHUB_ENV
          echo "DISTORIBUTION=${DISTORIBUTION}" >> $GITHUB_ENV
          echo "DEBIAN_CODE_NAME=${DEBIAN_CODE_NAME}" >> $GITHUB_ENV

    - run: |
        git config --global --add safe.directory "$GITHUB_WORKSPACE"
        git config --global user.name "${{ secrets.GIT_USERNAME }}"
        git config --global user.email "${{ secrets.GIT_EMAIL }}"

    - uses: actions/checkout@v3
      with:
        fetch-depth: '0'

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      with:
        install: true

    - uses: actions/cache@v3
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Login to DockerHub
      uses: docker/login-action@v2 
      with:
        username: poad
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: "Build and push ${{ matrix.versions.tag }}"
      uses: docker/build-push-action@v4
      with:
        push: true
        pull: true
        context: ${{ matrix.versions.dir }}
        platforms: ${{ matrix.versions.platforms }}
        tags: poad/docker-grpc:${{ matrix.versions.tag }}
        target: ${{ matrix.versions.target }}
        file: Dockerfile.release
        build-args: |
          BUILDKIT_INLINE_CACHE=1
          LLVM_VERSION=${{ env.LLVM_VERSION }}
          PROTOCOL_BUFFERS_VERSION=${{ env.PROTOCOL_BUFFERS_VERSION }}
          COMPOSE_VERSION=${{ env.COMPOSE_VERSION }}
          JAVA_VERSION=${{ env.JAVA_VERSION }}
          DISTORIBUTION=${{ env.DISTORIBUTION }}
          DEBIAN_CODE_NAME=${{ env.DEBIAN_CODE_NAME }}
