name: Docker build and push
 
on:
  push:
    branches:
    - main 
  pull_request:
    branches:
      - main
  schedule:
    - cron:  '0 0 * * 2'

jobs:
  docker_build_push:
    strategy:
      matrix:
        versions: [
          { tag: 'debian-buster', target: 'default' },
          { tag: 'compose', target: 'compose' }
        ]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Build
      run: |
        CUR=$(pwd) && \
        IMAGRE_NAME=poad/docker-grpc:${{ matrix.versions.tag }} && \
        docker build -t ${IMAGRE_NAME} . --target=${{ matrix.versions.target }} && \
        cd ${CUR}
    - name: Hadolint
      uses: brpaz/hadolint-action@master

    - name: Push
      if: github.event_name != 'pull_request'
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u poad --password-stdin && \
        IMAGRE_NAME=poad/docker-grpc:${{ matrix.versions.tag }} && \
        docker push ${IMAGRE_NAME}
